### ISSUE TITLE
Feature: Raid Management

### ISSUE THREAD

**Issue by onerandomusername** [python-discord/meta#101]
# What?

Defcon management without locking the server to everyone.
# Justification

I think that the Pydis server has gotten raided every day for the past 5 days. Are there any ways that the server could deal with a raid without locking all channels?  It seems like this is just going to be a daily/weekly thing due to the server size, and it seems like other servers don't have to deal with this so often.
# Implementation

I think the biggest idea is the defcon auto feature automatically enabling if enough users trigger a specific few rules. 

For example, if the too many mentions is triggered across several accounts within a set time frame, defcon would automatically enable kicking new users, but without locking the server. In addition, it could shush that channel for 15 minutes. 

It could also do this if the bad words filter is hit to a threshold, or the

**Comment by HassanAbouelela** [comment]
Without giving too much away, we are working on improving our tools and methodology, but ultimately we are limited by factors outside our control. The raids we've experienced the past few days would've all been automatically handled by our bot with no disruption to the server, if not for discord's rate limits.

We have automatic rules in place that prevent this sort of thing on a small scale, because usually, that's what we get. The larger it gets, the more it becomes a discord problem. The fact that one user/group can gain control over 100s of accounts very easily is something discord should be looking at themselves, and previously, the best mitigation methods have been implemented directly by discord.

Again, we are working on a few things internally, but the biggest change would have to come directly from discord. I'll be closing this issue now as there are no explicit suggestions, and nowhere for it to naturally progress from here.
