### ISSUE TITLE
today-I-learned channel where people say what they learned

### ISSUE THREAD

**Issue by was07** [python-discord/meta#158]
### Channel Name

today-I-learned

### What is the channel about?

A channel for people to say what interesting thing they learned

### Channel type

Other

### What justification do you have for the new channel? What do you see it being used for?

**What will be this channel for**
Sometimes people learn about a really interesting thing/topic and they want to share it with others. This channel will be specially for them.

**How the channel will be**
It can be though like a channel with a long slowmode where you can send a message saying "Hey, today I learn that you can do X using Y, it is very useful you should try it out."

People will give messages describing how/why they learned the topic and/or what the topic is and/or why the topic is useful.

**A Issue and solution**
This can be a hard channel to maintain for a reason:
Because every topic creates a topic to discuss, the channel can be filled with messages that are not the type said above. but this can be solved by a long slowmode and making the channel thread based.

**Comment by DMFriends** [comment]
Hey @was07, I really like this idea. However, I feel like this could be done in #python-general or one of the off-topic channels. I don't really see a necessity in creating a new channel for this. I am curious to see what other PyDis members and the core dev's think about this though.

**Comment by Shom770** [comment]
> Hey @was07, I really like this idea. However, I feel like this could be done in #python-general or one of the off-topic channels. I don't really see a necessity in creating a new channel for this. I am curious to see what other PyDis members and the core dev's think about this though.

You made some fair points, however there are a few problems with python-general or off topic:
1. The problem is that the channels are very fast and usually it's hard to share what you learned without someone talking over you on accident
2. This isn't a problem more so a benefit but a lot of other programming servers have a today-i-learned channel and with threads being implemented soon there is finally a place for just discussion about cool things in Python and what not

**Comment by was07** [comment]
> Hey @was07, I really like this idea. However, I feel like this could be done in #python-general or one of the off-topic channels. I don't really see a necessity in creating a new channel for this. I am curious to see what other PyDis members and the core dev's think about this though.

The big reason I opened this issue was because python-general is getting really fast/busy. And if you think off-topic channels as option, these today-I-learned messages aren't really off-topic.

And as @Shom770 says, a lot of servers have this channel, and the channel in Python server will become a place for just the discussion about cool things in Python and what not.

**Comment by DMFriends** [comment]
> The big reason I opened this issue was because python-general is getting really fast/busy. And if you think off-topic channels as option, these today-I-learned messages aren't really off-topic.
> 
> And as @Shom770 says, a lot of servers have this channel, and the channel in Python server will become a place for just the discussion about cool things in Python and what not.

Ok, I can certainly agree about #python-general being fast and busy. And yes, I do see your point about off-topic too. So let's start with that PyDis is the only programming server I'm currently in, so I didn't know about other programming servers having that kind of channel. Regardless, as I said, I still like this idea a lot.

I do think we could name this channel a bit differently. I think it should be called #cool-things-in-python as a more general name for the channel, instead of specifically "today". That's the one thing I'd probably change from what you described originally in the issue. Let me know what you think about that.

Other than that, this is great! Thanks for opening this issue!

(I wish I could give full approval but I'm not a mod lol)

**Comment by was07** [comment]
Changing the name doesn't matter, I just think Python Server needs this.

**Comment by DMFriends** [comment]
> Changing the name doesn't matter, I just think Python Server needs this.

Alright, that's fine. It's your call what you want to name it at the end of the day. That was just a suggestion. But yes, as I said, I do agree you but let's see what the core dev's think about this.

**Comment by was07** [comment]
The channel was added, with the original name, but I expected a credit in the announcement :/ Anyways, nice to contribute to my favorite sever!

**Comment by mbaruh** [comment]
You are right, I'll add credit 😄 what is your name on Discord?

**Comment by was07** [comment]
> You are right, I'll add credit 😄 what is your name on Discord?

`Was‘#9625`
You guys are doing an awesome job running the server!

**Comment by mbaruh** [comment]
Edited! I think this issue can be closed now.
