### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by meatballs** [python-discord/meta#189]
### Tag Name

nomodule

### What kind of content should the tag include?

We often get people asking about ModuleNotFoundError when they are convinced they've installed the relevant package. A common cause of that is installing the package into one environment but executing code from another.

How about a tag to explain that?

The !venv tag has some useful info, but you'd still need to explain why it's relevant to the problem in order to help.

**Comment by meatballs** [comment]
Oh well. No support for this, it seems. I shan't waste any more time on it.

**Comment by janine9vn** [comment]
I'm reviving this, because this is indeed something we (or at least I) want!

There are quite a few things that can be happening if a user gets a `ModuleNotFoundError`. I think it would be great to have a tag listing the different potential issues and avenues to see which one they're impacted by.

Off the top of my head here are the ones I can think of:
- used `pip` to install and that's pointing to a different python than they think it is
- PyCharm automatic venv creation
- They install with a different Python version than their editor is using
- General venv creation and how to interact with them

I think we can keep this tag short and just talk about where to start investigating, it doesn't need to enumerate the actual solutions. 

Thoughts?

**Comment by wookie184** [comment]
Relevant issue on bot repo: https://github.com/python-discord/meta/issues/219

I'd be happy to see a tag PRed. Ideally there would be a page on the site to explain things in detail but that could come later.
