### ISSUE TITLE
[Channel 🔰]Newbie-Help Channel Suggestion

### ISSUE THREAD

**Issue by Sas2k** [python-discord/meta#199]
### Channel Name

`#🔰-Newbie-Help`

### What is the channel about?

This channel is to get help for beginners to python.

### Channel type

Other

### What justification do you have for the new channel? What do you see it being used for?

Well, the channel can be really helpful for beginners since, a separate channel for beginners. can speed up the process of getting/receiving help.

Also this could be a chance to help others as well.

> If you wondering why this couldn't be done in Python-General or any of the Help Commands since,
> - A. The channels are very fast and it's usually hard to ask a question.
> - B. Sometimes when you ask a question in the Help channels To get a response some people have to wait a vey long time to get one.

That's it,
Hope you would agree!,
Good Day.

**Comment by Preocts** [comment]
A Newbie-Help channel applied to this does not seem to offer a solution to the valid two issues you raise.  It becomes "just another channel" to choose from.  I'd expect that it would have very low traffic and be by-passed for python-general, though I could be wrong.  My concern is that it becomes a gatekeeping method in other channels.  I wouldn't want anyone to be met with "Go ask in the Newbie-Help room until you're skilled enough to ask here" but that seems like the type of thing that would develop naturally. 

I would be curious, from your point of view, what would bring more value or understanding to the existing structure.  The theme of the request appears to be on the speed of responses, though correct me if I'm wrong.  Is there anything we could do to help underline that the server is powered by volunteers, how a question is asked can impact the response, and that the "slower" help channels will likely yield higher quality responses?  

(at least, that's the general goal of them!)

**Comment by Sas2k** [comment]
Hi @Preocts, You make a good point. But hey that's my point of view and my experience with the Help-channel system.

And asking someone to ask in another channel can hurt that person. Maybe this idea won't work.

But let's wait and see what other people think.

**Comment by Etzeitet** [comment]
I don't see how a dedicated `newbie-help` channel would improve speed of responses. 

`python-general` does move fast, but that's what the help channels are for. I strongly suspect a new beginners channel would end up with the same problem so we wouldn't be solving anything. So we don't solve a problem, but we now have a two-tier general help system which *will* lead to "us vs them" and gatekeeping.

From my experience of the help system, the most common reason questions go unanswered is due to the question being vague or not very well asked. A vague question asked in a new channel isn't going to get answered any quicker.

**Comment by Sas2k** [comment]
@Etzeitet I get your point.

Looks like this one of my bad ideas (lol)

Anyways since this suggestion would create more issues of it is implemented.

I will close this issue.
