### ISSUE TITLE
Add a tag to invite users to elaborate on broad/'can someone help' style questions

### ISSUE THREAD

**Issue by ghost** [python-discord/meta#209]
### Tag Name

ask

### What kind of content should the tag include?

**Basis:** /r/buildapc is one of the largest communities on Reddit, and I would surmise has a very similar Discord userbase; individuals joining less to engage the community as a whole and more to seek help with a specific issue. A recurrent issue I've observed is that individuals will ask a question to the effect of "Can someone help me?" which can often lead to multiple individuals inviting them to elaborate on the problem/etc., and cause the chat to be overinflated by this invitation. 

r/buildapc solves this with the following, paraphrased 'ask' command. 
_Please don't ask to ask. Ask your question and individuals will help you if they are available._

**Solution:** While the wording may change, I believe an effective solution would be to link to the PyDis resource on 'Asking Good Questions' within the tag itself, with similar verbiage as the buildapc bot. This can help generate more effective help threads, give necessary up-front information, and create a single succinct command which delivers all necessary information quickly without being too distracting within PyGen itself.

**Comment by wookie184** [comment]
We used to have an `!ask` tag but it was removed, see #136 for context. Having a general tag ended up confusing people more than it helped since it was misused (people would use it for any question that wasn't perfect, but it wasn't clear to the person asking what they actually did wrong). A proposal for a new ask tag would need to have this issue in mind.
