### ISSUE TITLE
!eval access for all in Python Help and Topical Chat/Help Channels

### ISSUE THREAD

**Issue by nottheswimmer** [python-discord/meta#28]
![image](https://user-images.githubusercontent.com/29849378/56096402-ad3c1c00-5eb5-11e9-8e73-f39097d069f1.png)

The `!eval` command is an invaluable tool for providing live examples of Python syntax and should not be limited to the `#bot-commands` channel only for regular users. It is useful not only as a demonstration tool, but also as a means of quickly ensuring the advice you're giving is complete and accurate. 

I propose that the command be enabled for everyone in the `Python Help` channels and the `Topical Chat/Help` channels, while keeping it reserved to privileged users in other channels.

**Comment by sco1** [comment]
I don't agree with unrestricting the output in the help channels for all users, but redirecting the output to #bot-commands (like `!free` does) is worth a discussion.

**Comment by nottheswimmer** [comment]
> I don't agree with unrestricting the output in the help channels for all users, but redirecting the output to #bot-commands (like `!free` does) is worth a discussion.

This would make it very difficult to read through a help thread if you have to constantly refer to output in `#bot-commands` in my opinion. Most of the vertical space is from the response of the bot itself, not a few extra lines in the command output.

**Comment by lemonsaurus** [comment]
This was brought up in the staff meeting today, 14th of April 2019.

While we greatly appreciate that this issue is motivated by a desire to better help our members, we ultimately feel that we should not change the way this works today. Here are the reasons we came up with:

- We feel that even a single user, even with good intentions, could generate a lot of noise with this tool. Perhaps the user would be trying to demonstrate something and running into various SyntaxErrors and other problems which would subsequently be corrected (and would then generate additional embeds). The noise potential of this command is such that we feel the filter is appropriate, even if the risk is low.
- We do think there's a few users on the server who would use this command to give better quality help, but we think there's far, far more users who would use it to generate noise. The ratio of learner to teacher is very large.
- We believe that many of those who fall into the category of being the few who might use it to give better quality help may end up being Helpers in the future, in which case they would be granted access to this tool.
- The Discord markdown code-blocks affords a good way to demonstrate things in an repl-like way to non-staff members already. The only real disadvantage is that you need to run your interpreter locally while you're helping out. This is such a feasible alternative that we do not agree that it's a big problem that the command is only accessible to staff, only a minor nuisance.


All of the above taken into account, we believe that access to this command may be more valuable to us as an incentive to becoming Helper than it would be as a service to our users. I am closing this ticket, but thank you for the suggestion.
