### ISSUE TITLE
Youtube activity

### ISSUE THREAD

**Issue by RohanJnr** [python-discord/meta#32]
Hey guys
Us being the hottest community on the internet, we should be kinda more active around.I mean youtube n stuff.We can start tutorials on youtube.I think it can really work out.For example discord.py, there are already quite a few tutorials for it but we can make a series like fun stuff/commands/features with discord.py.All the issues we work on(feature issues)(good features and more used), we can make videos on how to code that feature in d.py.
May not be d.py, can be anything
we members here can record while working on a feature and send it to the owner of the youtube channel and he can post it after having a look at it and making changes n stuff
what do you guys think?
maybe u can involve the community and also show some good projects which are being posted in #show-your-projects.
What do you guys think?

**Comment by lemonsaurus** [comment]
Thanks @RohanJnr. 

We do agree with you that we should be more active on our YouTube channel, and we do have a few videos planned for it. This issue is often brought up in the staff and we all agree that we'd like more YouTube activity, but every hour spent making YouTube content is an hour we're not spending on other key community features, like planning and running events, or improving our services.

There are only so many hours in a day. But rest assured that this is on our minds, and that we're going to try to allocate some time for this in the coming year - no promises, though.
