### ISSUE TITLE
Give paste.pydis.com a colorscheme with better contrast

### ISSUE THREAD

**Issue by Ivoz** [python-discord/meta#34]
I dunno about you guys  but

![paste.pydis.com example code](https://up.s-ul.eu/01Ux4xmg.png)

the default text seems extremely low contrast with the background. Even with new monitors I don't find it great.

From highlight.js' [available styles](https://github.com/highlightjs/highlight.js/tree/master/src/styles) ([demos](https://highlightjs.org/static/demo/)), better options than solarized to me, include: Atom One Dark, Gruvbox Dark, Kimbie Dark, Railscasts, Vs 2015. For a favourite I would pick Gruvbox. But any with some colours that pop a bit better and have better contrast of their text over the background colour.

**Comment by scragly** [comment]
The paste site's styling is going to be a very subjective thing, and no single theme chosen is going to suit everyone. As an example, the favourite one you've picked out is absolutely horrendous to my eyes, both dark and light versions.

There has been considerations in the past to instead add a style switcher and define a few different style options for people to personally pick as they wish, which would better cater to the varied tastes out there.

There was also considerations of making our own paste site instead with the features we personally like and implemented with python instead of using the javascript-based haste server, and a member of staff has actually started some basic rudimentary work on such a thing. 

We'd need to consider if it's worth bothering with altering haste ourselves to accommodate the previous feature or if we should just wait. For now, I think it's low enough priority that we just wait to see about the prospective home-grown solution.

If you wish to personalise the site to your own tastes, you're welcome to use a tool such as Stylus to do so also.

**Comment by Ivoz** [comment]
Altering the theme is simply a matter of changing a configuration string.

I will take *any* theme that is higher-contrast than solarized. I consider that objectively bad.

**Comment by Numerlor** [comment]
I quite like the `Atom One Dark`, it's also on another hastebin I'm using. A patterned background with the new pydis python splash screen could look nice too

**Comment by lemonsaurus** [comment]
We've decided not to action this right now.
