### ISSUE TITLE
#dev-announcements channel proposal

### ISSUE THREAD

**Issue by ks129** [python-discord/meta#51]
There should one more channel in `Development` category: `#dev-announcements`. This should have following automatic things:
- Message when someone get Contributor role
- Message when someone get Core Developer role
- Weekly summaries (per-repo)
- Monthly summaries (per-repo) (pinned until next monthly summary)

Fields that summaries should have:
- Issues|PRs opened
- Issues|PRs closed
- PRs merged
- Commits amount
- Top contributors
- Biggest PRs
and maybe even some generated graphs.

This channel should announcement channel so everyone can subscribe.

**Comment by lemonsaurus** [comment]
If this was fully automated, I suppose it would be okay. I think it would have a fairly niche appeal, though, and I'm not entirely convinced it's worth spending time on.

**Comment by ks129** [comment]
Yes of course this should fully automated. Manually doing this have no point.

**Comment by lemonsaurus** [comment]
I think manually doing this would have much greater value, since it would allow us to put these changes into context (why is this PR important to you?) and to thank our contributors. We were planning to release these monthly community updates which included information like this, but as it turns out, continuing to write these announcements takes up time and effort we don't always have available. We're already stretched pretty thin.

So, I disagree that it would have "no point" to do it manually, but I agree that we probably shouldn't do it. I don't want to add additional load to the staff for something like this.

**Comment by ks129** [comment]
@lemonsaurus But what about command with what is possible to attach such important PRs and contributors thanks messages to next summary?

**Comment by jb3** [comment]
I feel like an actual "announcements" channel should be more along the lines of what Scragly recently announced in #dev-contrib.

When we do something major to our services which our contributors need to be aware of, some notable examples:
- Discord.py version bumps
- Redis integration
- New verification system

If we have a lot of these things which we feel need announcing then there may be some merit to these changes. We could also build something small to generate contribution statistics monthly, and even automate this. I'd be interested in doing it.

**Comment by Akarys42** [comment]
I think this could be quite interesting to draw attention on our ongoing projects, and maybe this could provide us the boost of reviewing we need (CC @MrHemlock). We could have a “faster paced” announcement channel, with some highlights of what is going on in our projects, and what needs reviewing. Oh, and stats are cool.

**Comment by jb3** [comment]
After the meeting on 11th October, we've decided to go ahead with this proposal. We'll be documenting changes to our open source projects, talking about code reviews and where possible we'll publish statistics on these things!
