### ISSUE TITLE
New data repository

### ISSUE THREAD

**Issue by ks129** [python-discord/meta#58]
Currently all data (tags, in future guides + resource for site, JSON files) is in different repositories in different locations. Also all of these currently need redeployment in order to apply modifications. I think all these resources should be in `python-discord/data` repository. How this would work:

- For tags, this should load all tags from data repository during cog loading. This will mean that after applying new changes for tags, only thing that some of the staff have to do is reload cog and all will be loaded again.
- For site stuff, this should load data every time when somebody visit page.
- For JSON resources, these should be too loaded on cog load.

**Comment by Akarys42** [comment]
I don't think it is a good idea, for 3 reasons:
* In some cases, this would lead to 2 separate PRs for the same functionality, such as a format change. 
* This will add some probably unneeded complexity to the code, with the issue of local development.
* All the resources are already in my opinion very well organised already; the guides served by the website are on the site, the tags served by python are on the bot, while everything used by seasonal is already on seasonalbot. I don't really see any need in changing that.

**Comment by jb3** [comment]
I agree with all the points made my Akarys here.

As we dewikify I don't think there will be a huge issue with finding the information. It will all be on GitHub and organised into the relevant repositories. I think unifying it into one repository is a lot of work for very little benefit.

For that reason I'm going to close this, since it's not something that will provide us much benefit for the complexities it adds. Techniques like "loading the data on every page load" will get us into ratelimits and resource caps and it's much more efficient not to.
