### ISSUE TITLE
Suggestion: Pruning of excessively long blocks of code or text

### ISSUE THREAD

**Issue by antoniouaa** [python-discord/meta#78]
#python-general is the landing chat for the server and so it makes sense that new users use that channel for their python problems.
The problem arises when they start dumping huge blocks of code or text in the middle of active conversations, effectively disrupting the flow of the channel.

example of enormous code block: https://discord.com/channels/267624335836053506/267624335836053506/793294127004385310

Seeing as a large chunk of discord users are on their phones and how vertical space is extremely important (example screenshot from my own 6" phone) I feel it appropriate to make this suggestion that the bot in the server prunes messages of a certain size or higher and instead offer a small embed or DM to that user that explains what happened and links them to a pastebin service.

![discord issue](https://user-images.githubusercontent.com/15040368/103304892-b1013080-4a01-11eb-8d3b-95adcb921d02.jpg)

**Comment by swfarnsworth** [comment]
For what it's worth, I typically delete large messages in python-general when I see them and direct the commenter to another channel. It looks like Joe is thinking we'll discuss this more internally, but if you have an idea for how you want us to solve this issue more permanently (such as new functionality for the bot), please let us know.

**Comment by antoniouaa** [comment]
It has been three days since I opened this issue and for as long as I've been active in the server for those days I haven't seen a single long post pruned/deleted.

**Comment by swfarnsworth** [comment]
We have not had a staff meeting since you opened the issue.

**Comment by antoniouaa** [comment]
I was referring to

> For what it's worth, I typically delete large messages in python-general when I see them and direct the commenter to another channel. It looks like Joe is thinking we'll discuss this more internally, but if you have an idea for how you want us to solve this issue more permanently (such as new functionality for the bot), please let us know.

Just pointing out that this doesn't happen often enough. Maybe I'm not online at the right times but it seems that mods don't manually take care of posts like these that often.

**Comment by SebastiaanZ** [comment]
I think there's a bit of a mismatch in expectations here. 

We typically make policy changes after discussing it within the moderation team and the staff team in general, but we're all just volunteers and a lot of us have been celebrating Christmas and New Year's Eve over the past week. We simply haven't had time to discuss your proposed changes to our moderation policy.

Our current moderation policy does not include trimming these messages, as removing messages comes with issues of its own (people losing a message they've spend a long time writing). However, I think it's okay to ask people to use a paste service for longer pieces of code and/or ask them to open a help channel for help conversations that could benefit from having a dedicated channel.

Still, actually actively starting to remove messages that otherwise don't violate our current rules is something that we need to discuss first.

**Comment by swfarnsworth** [comment]
When I said "I typically delete large messages in python-general when I see them and direct the commenter to another channel", I was referring to something that I do personally when I happen to be viewing python-general. It is not a formal procedure that the moderation team has agreed upon.

I believe the current plan is to discuss this issue in the next staff meeting, and any other suggestions you have would be taken into consideration at that time. One possibility we will likely consider (but not necessarily implement) is a new rule for the bot whereby vertically long messages are automatically deleted from that particular channel, though there are potential problems with that, such as the user unexpectedly losing the content of their message or finding the automated moderation callous and unwelcoming.

**Comment by antoniouaa** [comment]
I understand that it's the holidays and people are AFK. My point is that we shouldn't have to rely on mods taking the time to handle such low level tasks, we understand that you're busy people.

As for the issue of the user being annoyed that they might lose their message content, there are ways to deal with that. The bot could DM them the entire message after deleting it from the channel so they don't have to deal with rewriting it.

As for the issue of the user being annoyed by automated moderation or feeling unwelcome, I don't think it's fair to ignore how other users feel when their small question is being completely blocked by random blocks of text, or how the conversation is clogged because a new user didn't use a paste service.

**Comment by lemonsaurus** [comment]
> As for the issue of the user being annoyed by automated moderation or feeling unwelcome, I don't think it's fair to ignore how other users feel when their small question is being completely blocked by random blocks of text

So, the proposal is to trade one poor user experience for another? I don't like it. I think inevitably someone is going to be annoyed here, and I'm not sure it's wise for us to invest dev hours into _shifting that annoyance around_.

Furthermore, I think the real solution to the problem of having small questions blocked by the hectic nature of #python-general is to stop asking small questions in #python-general and move to help channels and topical channels, where you can enjoy relative peace and quiet. It's okay to ask questions in #python-general, don't get me wrong - but I don't think it's necessary for us to invest that much time in trying to optimize that experience. 

In some way, you could argue this is suboptimal by design, as a means of motivating members to look elsewhere for help. It's a sort of load balancing - If everyone looked in the same channel for help, there'd be total chaos, we don't have the capacity for that. We need this road to be a bit rocky, we need that friction, or nobody will bother to look elsewhere for better quality help.

Overall, I'm not in favor of this change. We've discussed it among the staff tonight, and the overall consensus is that this isn't worth investing our time into. That said, I appreciate you taking the time to open this issue, and hearing your suggestions for how we can continue to improve this community!
