### ISSUE TITLE
Improving help channels

### ISSUE THREAD

**Issue by JacobMonck** [python-discord/meta#95]
Hey,

I was recently thinking about a smarter way the the help channels could be done. I was thinking that there could be one more channel category that could be called "Ready For Help". How this would work, I was thinking as a help channel is opened and if the user asks a question the channel would go into the "Ready For Help" until its receives a response from a different user.

**Comment by onerandomusername** [comment]
This was talked about a bit in #community-meta, and this is what I came up with

> A channel somewhere which lists all of the active help channels, and as an added bonus, who claimed them. 
By design, each newly claimed channel would be a new message, with a pinned message as a master list. It would also mention if they had been responded to As they get answered, they would be deleted and removed from the list.

Context: 
> https://discord.com/channels/267624335836053506/429409067623251969/819131782871908362

**Comment by dawnofmidnight** [comment]
This was implemented with the new message at the bottom of `#how-to-get-help`.
![image](https://user-images.githubusercontent.com/78233879/121074581-0fe18780-c7a2-11eb-9c1e-8629fcc696fb.png)

**Comment by JacobMonck** [comment]
This was meant to be closed but never was.
