### ISSUE TITLE
Change phrasing and grammar of good/bad behavior examples in the Code of Conduct

### ISSUE THREAD

**Issue by am-a-wnb** [python-discord/meta#98]
# What?

This is a proposal to change the grammar of examples of good and bad behavior of PyDis's Code of Conduct. There are some significant changes listed below, but most of the changes are minor.

I should preface this issue by saying that I am not a certified grammaticist, nor have I academically studied English's grammar for a profession. I simply think that these changes would help members of the community to understand the Code of Conduct better.

Here is [the proposed version](https://paste.pythondiscord.com/ogisegexut.sql).

The proposed version of the behavior list uses grammatical parallelism and shortens some examples.

There are also some removals in the proposed version:
- I have removed "sexual attention" in "The use of sexualized language or imagery and sexual attention or advances". I only removed this because I think that this phrase is vague.
- I have removed "Other conduct which could reasonably be considered inappropriate". I removed this since the "Our Goal" paragraph states that "this is not an exhaustive things you can and can't do".

I am only proposing a change in the examples of good and bad behavior because I think that every other part of the CoC is perfectly fine.

# Justification

This change would help members of the community understand the Code of Conduct better.

# Implementation

If this change is implemented, the grammar of the examples of behavior listed in Discord server's #code-of-conduct would be changed. The grammar of the examples listed in [the code of conduct of PyDis repositories](https://github.com/python-discord/.github/blob/673ddb9b8ead005f9dec54107ac0b72bfe070d2c/CODE_OF_CONDUCT.md) would also be changed.

**Comment by SebastiaanZ** [comment]
Hello @am-a-wnb,

Thank you for your suggestions to our Code of Conduct. We had a discussion about the changes you proposed during our staff meetings, and we decided the following:

- We don't want to remove the parts you proposed to remove. We think it's important to mention "sexual attention" in a Code of Conduct, and it's also a phrase that's not uncommon to find on Code of Conducts, including those we took as inspiration for our own (e.g., the [Adafruit Code of Conduct](https://github.com/adafruit/Adafruit_Community_Code_of_Conduct/blob/master/code-of-conduct.md) and the [Django Code of Conduct](https://www.djangoproject.com/conduct/)).
  
  The "catch-all" line of "Other conduct ..." is included specifically because we want to emphasize the point that it's not an exhaustive list; it's a common argument we run into with our moderation team. We don't quite mind that it's a redundancy because of that.
  
- We were divided on the grammar changes proposed. At the end, it means that I think we should not make changes to the document because of it. A Code of Conduct is a document that should change a few times as possible, which means that the changes should be significant enough to warrant such a change. In addition, the current phrasing is heavily inspired by, adapted from, or even cited from the Code of Conducts we refer to in the attribution section. I think there's value in following such examples unless the advantages of a bespoke variant are significant. We don't believe that's the case here.
